version: '3'

services:

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: ./.env
    restart: always
    ports:
      - 4000:3000
    depends_on:
      - db
    networks:
      - dbnet

  db:
    container_name: database
    image: postgres:15-alpine
    env_file: ./.env
    restart: always
    volumes:
      - pgdata:/var/lib/postgres/data
    networks:
      - dbnet

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8081:80

volumes:
  pgdata:

networks:
  dbnet: {}
